Refactor validation status handling and update workflow to reflect final status [skip ci]

diff --git a/.github/workflows/createValidationTableAndChecks.yaml b/.github/workflows/createValidationTableAndChecks.yaml
--- a/.github/workflows/createValidationTableAndChecks.yaml
+++ b/.github/workflows/createValidationTableAndChecks.yaml
@@ -14,6 +14,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+      FINAL_STATUS: "ERROR"
     permissions:
       contents: write      # Allows pushing to the repository
       pull-requests: write # If you need to comment on PRs
@@ -75,6 +76,12 @@ jobs:
           git push origin ${branch_name}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    
+
+      - name: If any error fail the workflow
+        if: ${{ env.FINAL_STATUS }} == 'ERROR'
+        run: |
+          cat VOCABULARIES/VOCABULARIES_VALIDATION_STATUS.md
+          echo "Final status is Error"
+          exit 1
 
       
